services:
  - type: web
    name: namfonshop
    env: docker
    plan: free
    autoDeploy: true
    repo: https://github.com/artkittisak2541/namfonshop.git
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: apache2-foreground
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: namfonshop-db
          property: connectionString

databases:
  - name: namfonshop-db
    plan: free
    databaseName: shop_db
    user: shop_user
