services:
  - type: web
    name: namfonshop
    env: docker
    plan: free
    repo: https://github.com/artkittisak2541/namfonshop
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: namfonshop-db
          property: connectionString
    initScript: init_postgresql.sql
