services:
  - type: web
    name: namfonshop
    env: docker
    plan: free
    autoDeploy: true
    repo: https://github.com/artkittisak2541/namfonshop.git
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: apache2-foreground
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: namfonshop_db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: namfonshop_db
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: namfonshop_db
          property: database
      - key: PGUSER
        fromDatabase:
          name: namfonshop_db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: namfonshop_db
          property: password
      - key: PGPORT
        fromDatabase:
          name: namfonshop_db
          property: port

databases:
  - name: namfonshop_db
    plan: free
    databaseName: namfonshop_db
    user: namfonshop_db_user
